const types = {
    FETCH_CITY_CODE: 'FETCH_CITY_CODE',
    FETCH_CITY_WEATHER: 'FETCH_CITY_WEATHER',
    FETCH_FIVE_DAY_FORECAST: 'FETCH_FIVE_DAY_FORECAST',
    USER_INPUT: 'USER_INPUT',
    ADD_FAVORITE_CITY: 'ADD_FAVORITE_CITY',
    DELETE_FAVORITE_CITY: 'DELETE_FAVORITE_CITY',
    SELECTED_CITY: 'SELECTED_CITY',
    SET_DARK_MODE: 'SET_DARK_MODE',
    SET_FAHRENHEIT_CELSIUS: 'SET_FAHRENHEIT_CELSIUS'
};
export default types;